exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    exclude: '\.ipynb$'
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: '\.ipynb$'
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: no-commit-to-branch
    args: ['--branch', 'master']

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.7.1
  hooks:
    - id: reorder-python-imports
      exclude: "(migrations)"

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3

# If like to embrace black styles even in the docs:
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [
      --per-file-ignore,
      "*/__init__.py:F401"
    ]
