name: Project Automations

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request_target: #_target allows access to secrets
    types:
      - opened
      - reopened
      - closed
      - review_requested
    branches:
      - main
      - dev

env:
  todo: Todo
  done: Done
  in_progress: In Progress
  USER: iwishiwasaneagle
  PROJECT_ID: 3

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_ID: ${{ secrets.GH_APP_ID }}
          gh_app_installation_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.GH_APP_SECRET_KEY }}
          user: ${{ env.USER }}
          project_id: ${{ env.PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_ID: ${{ secrets.GH_APP_ID }}
          gh_app_installation_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.GH_APP_SECRET_KEY }}
          user: ${{ env.USER }}
          project_id: ${{ env.PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  pr_opened_or_reopened_or_reviewrequested:
    name: pr_opened_or_reopened_or_reviewrequested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to ${{ env.in_progress }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_ID: ${{ secrets.GH_APP_ID }}
          gh_app_installation_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.GH_APP_SECRET_KEY }}
          user: ${{ env.USER }}
          project_id: ${{ env.PROJECT_ID }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_progress }} # Target status
  pr_closed:
    name: pr_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Move PR to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_ID: ${{ secrets.GH_APP_ID }}
          gh_app_installation_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.GH_APP_SECRET_KEY }}
          user: ${{ env.USER }}
          project_id: ${{ env.PROJECT_ID }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.done }} # Target status
